config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :plans
  post "checkout/create", to: "checkout#create"
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  validate :picture_size

  private

  def picture_size
    if picture.size > 5.megabytes
      error.add(:picture, "The image should be less than 5Mo ")
    end
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user

  validates :name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_one :plan
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email,:avatar])

  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  
  def create
    
    plan = Plan.find(params[:id])
    @session = Stripe::Checkout::Session.create({
      line_items: [{
          name: plan.name,
          amount: plan.price,
          currency: 'usd',
          quantity: 1
      }],
      payment_method_types: [
        'card',
      ],
      mode: 'payment',
      success_url: root_url,
      cancel_url: root_url,
    })
   
    respond_to do |format|
      
      format.js
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:title, :description, :user_id, :picture)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  # before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @plans = Plan.all
  end

  # GET /products/1 or /products/1.json
  def show
    @plan = Plan.find(params[:id])
  end

  # GET /products/new
  def new
    @plan = Plan.new
  end

  # GET /products/1/edit
  def edit
    @plan = Plan.find(params[:id])

  end

  # POST /products or /products.json
  def create
    @plan = Plan.new(product_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_product
    #   @plan = Plan.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:plan).permit(:name, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @home_page = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/checkout/create.js.erb
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public_key] %>");

stripe.redirectToCheckout({
  sessionId:'<%= @session.id %>'
}).then(function (result){
  console.log(result.error.message)
}); 

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
<div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">

  $('#image_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert("Maximum file size is 5Mo")
    }
  })

</script>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag(image.picture, width: "40px" ) if image.picture.attached? %></td>
        <td><%= image.title %></td>
        <td><%= image.description %></td>
        <td><%= image.user.username %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag(@image.picture, width: "100px") if @image.picture.attached? %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user.username %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class:"nav-link" %>
      </li><li class="nav-item active">
        <%= link_to 'Plans', plans_path, class:"nav-link" %>
      </li><li class="nav-item active">
        <%= link_to 'Images', images_path, class:"nav-link" %>
      </li>
    
    </ul>
  
      <ul class= "nav navbar-right">
        <% if current_user %>
         <li class="nav-item dropdown">
         
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= image_tag current_user.avatar, width: "40px", class: "rounded-circle" %> <%= (truncate(current_user.username, length: 25)).html_safe  %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
          <% else %>
          <li class= "pull-right mr-2" ><%= link_to "Login", new_user_session_path, class: "btn btn-primary" %></li>
          <li class= "pull-right" ><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %></li>
        <% end %>
      </ul>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= @home_page ? 'homepage' : ''%>">
  <%= render "layouts/navigation" %>
    <div class="container">
      <div class="row">
      <div class="col-lg-12">
    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form', plan: @plan %>
<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Plans#index</h1>
<p>Find me in app/views/plans/index.html.erb</p>
<div class="container ">
    <div class="plans clearfix row  justify-content-center">
    <% @plans.each do |pla| %>
      <div class="col-lg-3 col-lg-offset-3 plan">
      
        <h2><%= pla.name %></h2>
        <div class="price pull-right">
          Price: <%= pla.price %>$
        </div>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p>
          <%= button_to 'Buy', checkout_create_path,class: 'btn btn-primary sign-up', params: {id: pla.id}, remote: true %>
          <% if current_user.username == 'admin' %>
            <%= link_to 'Edit', edit_plan_path(pla),class: 'btn btn-success sign-up'%>

          <% end %>
        </p>
        
      </div>
      <% end %>
    </div>
  </div>

 

app/views/plans/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @plan %>

<%= link_to 'Back', plan_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plan.price %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h2>Welcome to the Photo Management App!</h2>
    <p class="lead">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </p>
  </div>

  